language: node_js
sudo: false
node_js:
  - "8.10"
install:
  - sh ./install.sh
deploy:
  provider: script
  script: bash ./deploy.sh production
  on:
    branch: master
script:
  - echo "You did it!"
